//
//  File.swift
//
//
//  Created by MOBILE on 20/05/24.
//

import Foundation

class ArabicDataValues {
    func getDictionary() -> [String: String] {
        return [
            "RFID_Error_AlreadyDone" : "RFID: العملية المطلوبة تمت بالفعل",
            "RFID_Error_Busy" : "RFID: RFID مشغول",
            "RFID_Error_Failed" : "تتفاعل: فشل",
            "RFID_Error_FileIOError" : "ملف RFID: خطأ IO",
            "RFID_Error_InvalidDirectory" : "RFID: دليل غير صالح",
            "RFID_Error_InvalidParameter" : "RFID: تم العثور على معلمة غير صالحة في استدعاء ExecuteCommand()",
            "RFID_Error_NoChipDetected" : "RFID: لم يتم اكتشاف أي شريحة",
            "RFID_Error_NotAvailable" : "تتفاعل: غير متوفر",
            "RFID_Error_NotEnoughMemory" : "تتفاعل: نفاد الذاكرة",
            "RFID_Error_NotInitialized" : "RFID: الجهاز غير مهيأ",
            "RFID_Error_NotPerformed" : "RFID: لم يتم الأداء",
            "RFID_Error_OldFirmware" : "RFID: يجب تحديث البرنامج الثابت إلى إصدار أحدث",
            "RFID_Error_PCSC_CantConnectCard" : "PCSC: لا يمكن توصيل البطاقة",
            "RFID_Error_PCSC_CardIsBusy" : "PCSC: البطاقة مشغولة",
            "RFID_Error_PCSC_CardIsNotConnected" : "PCSC: البطاقة غير متصلة",
            "RFID_Error_PCSC_ExtLe_Failed" : "PCSC: فشل ExtLe",
            "RFID_Error_PCSC_Failed" : "PCSC: فشل",
            "RFID_Error_PCSC_FailedSCard" : "PCSC: فشل البطاقة الذكية",
            "RFID_Error_PCSC_OperationCancelled" : "PCSC: تم إلغاء العملية",
            "RFID_Error_PCSC_ReaderNotAvailable" : "PCSC: القارئ غير متاح",
            "RFID_Error_Session_AccessControl_AA_Failed" : "RFID: فشل AA",
            "RFID_Error_Session_AccessControl_CA_Failed" : "RFID: فشل CA",
            "RFID_Error_Session_AccessControl_IncorrectOptionCA" : "RFID: خيار CA غير صحيح",
            "RFID_Error_Session_AccessControl_RI_Failed" : "RFID: فشل RI",
            "RFID_Error_Session_AccessControl_RequiresCA" : "RFID: يتطلب CA",
            "RFID_Error_Session_AccessControl_RequiresCAKeys" : "RFID: يتطلب مفاتيح CA",
            "RFID_Error_Session_AccessControl_RequiresPACE" : "RFID: يتطلب PACE",
            "RFID_Error_Session_AccessControl_RequiresSM" : "RFID: يتطلب SM",
            "RFID_Error_Session_AccessControl_RequiresTA" : "RFID: يتطلب TA",
            "RFID_Error_Session_AccessControl_UnknownType" : "RFID: نوع التحكم في الوصول غير معروف",
                "RFID_Error_Session_AccessKey_IncorrectData" : "RFID: بيانات المفتاح غير صحيحة",
                "RFID_Error_Session_AccessKey_IncorrectSMType" : "RFID: نوع SM للمفتاح غير صحيح",
                "RFID_Error_Session_AccessKey_NotSet" : "RFID: المفتاح لم يتم تعيينه",
                "RFID_Error_Session_AccessKey_Restricted" : "RFID: المفتاح مقيد",
                "RFID_Error_Session_AccessKey_UnknownType" : "RFID: نوع المفتاح غير معروف",
                "RFID_Error_Session_AccessKey_UnsupportedSMType" : "RFID: نوع SM للمفتاح غير مدعوم",
                "RFID_Error_Session_File_AccessDenied" : "ملف RFID: تم رفض الوصول",
                "RFID_Error_Session_File_CantReadData" : "ملف RFID: لا يمكن قراءة البيانات",
                "RFID_Error_Session_File_CantUseData" : "ملف RFID: لا يمكن استخدام البيانات",
                "RFID_Error_Session_File_Contents_UnexpectedData" : "ملف RFID: محتويات البيانات غير المتوقعة",
                "RFID_Error_Session_File_IncorrectData" : "ملف RFID: البيانات غير صحيحة",
                "RFID_Error_Session_File_NotEnoughData" : "ملف RFID: البيانات غير كافية",
                "RFID_Error_Session_File_UnexpectedData" : "ملف RFID: البيانات غير متوقعة",
                "RFID_Error_Session_File_WrongTag" : "ملف RFID: العلامة خاطئة",
                "RFID_Error_Session_IncorrectData" : "RFID: البيانات غير صحيحة",
                "RFID_Error_Session_InvalidAuxData_CommunityID" : "RFID: معرف المجتمع المساعد غير صالح",
                "RFID_Error_Session_InvalidAuxData_DateOfBirth" : "RFID: تاريخ الميلاد المساعد غير صالح",
                "RFID_Error_Session_InvalidAuxData_DateOfExpiry" : "RFID: تاريخ انتهاء المساعد غير صالح",
                "RFID_Error_Session_IsClosed" : "RFID: الجلسة مغلقة",
                "RFID_Error_Session_PA_HashCheckFailed" : "RFID: فشل التحقق من الهاش",
                "RFID_Error_Session_PA_SignatureCheckFailed" : "RFID: فشل التحقق من التوقيع",
                "RFID_Error_Session_ProcedureType_NotSet" : "RFID: نوع الإجراء لم يتم تعيينه",
                "RFID_Error_Session_ProcedureType_Unknown" : "RFID: نوع الإجراء غير معروف",
                "RFID_Error_Session_ProcedureType_Unsupported" : "RFID: نوع الإجراء غير مدعوم",
                "RFID_Error_Session_PwdManagement_NotAuthorized" : "RFID: إدارة كلمة المرور غير مصرح بها",
                "RFID_Error_Session_TerminalType_BadCertificate" : "RFID: شهادة نوع المحطة سيئة",
                "RFID_Error_Session_TerminalType_NotSet" : "RFID: نوع المحطة لم يتم تعيينه",
                "RFID_Error_Session_TerminalType_Unknown" : "RFID: نوع المحطة غير معروف",
            "RFID_Error_Session_Terminal_UnsupportedOperation" : "RFID: عملية غير مدعومة من المحطة",
            "RFID_Error_Session_eSign_PIN_NotSet" : "RFID: لم يتم تعيين رقم التعريف الشخصي للتوقيع الإلكتروني",
            "RFID_Error_Session_eSign_PIN_NotVerified" : "RFID: رقم التعريف الشخصي للتوقيع الإلكتروني لم يتم التحقق منه",
            "RFID_Error_Session_eSign_RequiresAppSelection" : "RFID: يتطلب التوقيع الإلكتروني اختيار التطبيق",
            "RFID_Error_UnknownCommand" : "RFID: أمر غير معروف",
            "RFID_LAYER6_APP_SELECTION_FAILURE" : "LAYER6: ISO7816_A_03 \"فشل اختيار التطبيق\"",
            "RFID_LAYER6_EXT_AUTH_FAILURE" : "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (فشل المصادقة الخارجية)",
            "RFID_LAYER6_FILE_EOF1" : "LAYER6: القراءة تتجاوز EOF / نهاية غير متوقعة للملف",
            "RFID_LAYER6_FILE_EOF2" : "LAYER6: القراءة تتجاوز EOF / نهاية غير متوقعة للملف",
            "RFID_LAYER6_FILE_NOT_FOUND" : "LAYER6: فشل اختيار الملف / الملف غير موجود",
            "RFID_LAYER6_GENERAL_AUTH_FAILURE" : "LAYER6: فشل المصادقة العامة",
            "RFID_LAYER6_GET_CHALLENGE_FAILURE" : "LAYER6: فشل الحصول على التحدي",
            "RFID_LAYER6_INCORRECT_PARAMS" : "LAYER6: معلمات غير صحيحة",
            "RFID_LAYER6_INT_AUTH_FAILURE" : "LAYER6: فشل APDU_INS_INTERNAL_AUTHENTICATE",
            "RFID_LAYER6_MSE_SET_AT_FAILURE" : "LAYER6: فشل MSE:Set AT",
            "RFID_LAYER6_MSE_SET_DST_FAILURE" : "LAYER6: فشل MSE:Set DST",
            "RFID_LAYER6_MSE_SET_KAT_FAILURE" : "LAYER6: فشل MSE:Set KAT",
            "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL" : "LAYER6: ISO7816_B_02 \"فشل تشفير المصادقة المتبادلة\"",
            "RFID_LAYER6_MUTUAL_AUTH_FAILURE" : "LAYER6: ISO7816_B_03 \"فشل المصادقة المتبادلة\"",
            "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL" : "LAYER6: ISO7816_B_01 \"فشل MAC المصادقة المتبادلة\"",
            "RFID_LAYER6_NON_TLV_RESPONSE_DATA" : "LAYER6: بيانات استجابة غير TLV",
            "RFID_LAYER6_NO_REFERENCE_DATA" : "LAYER6: لا توجد بيانات مرجعية",
            "RFID_LAYER6_PSO_CERTIFICATE_FAILURE" : "LAYER6: فشل شهادة PSO",
            "RFID_LAYER6_PWD_BLOCKED" : "LAYER6: كلمة المرور محظورة",
            "RFID_LAYER6_PWD_BLOCKED_2" : "LAYER6: كلمة المرور محظورة 2",
            "RFID_LAYER6_PWD_DEACTIVATED" : "LAYER6: كلمة المرور معطلة",
            "RFID_LAYER6_PWD_DEACTIVATED_2" : "LAYER6: كلمة المرور معطلة 2",
            "RFID_LAYER6_PWD_FAILED" : "LAYER6: فشل كلمة المرور",
            "RFID_LAYER6_PWD_SUSPENDED" : "LAYER6: كلمة المرور معلقة",
            "RFID_LAYER6_PWD_SUSPENDED_2" : "LAYER6: كلمة المرور معلقة 2",
            "RFID_LAYER6_SECURITY_MANAGER" : "LAYER6: لم يتم تفعيل المراسلة الآمنة",
            "RFID_LAYER6_SM_DO87_INCORRECT" : "LAYER6: فشل SM – تشفير غير صحيح",
            "RFID_LAYER6_SM_DO87_MISSING" : "LAYER6: فشل SM – التشفير مفقود",
            "RFID_LAYER6_SM_DO8E_MISSING" : "LAYER6: فشل SM – MAC مفقود",
            "RFID_LAYER6_SM_DO99_MISSING" : "LAYER6: فشل SM – رموز الحالة المؤمنة مفقودة",
            "RFID_LAYER6_SM_MAC_INCORRECT" : "LAYER6: فشل SM – MAC غير صحيح",
            "RFID_LAYER6_WRONG_RND_ICC_LENGTH" : "LAYER6: طول البيانات غير صحيح (APDU_INS_GET_CHALLENGE)",
            "RSDT_RFID_READING_FINISHED" : "اكتمل قراءة بيانات RFID",
            "TCT_Unknown" : "غير معروف",
            "chd_BackgroundComparisonError" : "اختلاف سطوع الصفحتين",
            "chd_BadAreaInAxial" : "فشل الحماية الارتجاعية",
            "chd_BarcodeDataFormatError" : "خطأ في تنسيق الباركود",
            "chd_BarcodeReadedWithErrors" : "تم قراءة الباركود بأخطاء",
            "chd_BarcodeSizeParamsError" : "خطأ في معلمات حجم الباركود",
            "chd_DocumentIsCancelling" : "تم إلغاء الوثيقة",
            "chd_ElementShouldBeColored" : "يجب أن يكون العنصر ملونًا",
            "chd_ElementShouldBeGrayscale" : "يجب أن يكون العنصر رماديًا",
            "chd_ExceptionInModule" : "تم اعتراض الاستثناء",
            "chd_FalseIPIParameters" : "معلمات IPI خاطئة",
            "chd_FalseLuminiscenceError" : "وجود أشياء لامعة زائدة",
            "chd_FalseLuminiscenceInBlank" : "توهج زائف في الأشعة فوق البنفسجية",
            "chd_FalseLuminiscenceInMRZ" : "توهج زائد في منطقة MRZ",
            "chd_FibersNotFound" : "الألياف غير موجودة",
            "chd_FieldPosCorrector_Highlight_IR" : "إضاءة زائدة في الأشعة تحت الحمراء",
            "chd_FieldsComparisonLogicError" : "خطأ منطقي عند مقارنة الحقول",
            "chd_FixedPatternError" : "عدم تطابق الكائن المحدد",
            "chd_HologramElementAbsent" : "الهولوجرام غير موجود",
            "chd_HologramElementPresent" : "الهولوجرام موجود",
            "chd_Hologram_Side_Top_Images_Absent" : "لا توجد صور جانبية أو علوية",
            "chd_IncorrectBackgroundLight" : "سطوع الخلفية غير صحيح",
            "chd_IncorrectTextColor" : "لون النص غير صحيح",
            "chd_InternalError" : "خطأ في معالجة البيانات الداخلية",
            "chd_InvalidChecksum" : "قيمة التحقق غير صالحة",
            "chd_InvalidFieldFormat" : "تنسيق الحقل لا يتطابق مع وصف الوثيقة",
            "chd_InvalidInputData" : "بيانات إدخال غير صالحة",
            "chd_InvisibleElementPresent" : "يجب أن يكون الكائن غير مرئي",
            "chd_LogicError" : "خطأ منطقي في البيانات",
            "chd_LowContrastInIRLight" : "تباين غير صحيح للكائن في الضوء تحت الحمراء",
            "chd_MobileImages_LowLightConditions" : "ظروف الإضاءة غير ملائمة لالتقاط الصور",
            "chd_MobileImages_WhileUVNoDifference" : "فرق منخفض بين الصور في أنظمة الإضاءة المختلفة",
            "chd_NecessaryImageNotFound" : "الصورة المطلوبة لهذا الفحص مفقودة",
            "chd_NotAllBarcodesRead" : "يجب أن يحتوي هذا المستند على المزيد من الباركود",
            "chd_OVI_BadColor_Front" : "عدم تطابق لون كائن OVI تحت الضوء الأبيض",
            "chd_OVI_BadColor_Percent" : "نسبة تطابق منخفضة بين عناصر OVI",
            "chd_OVI_BadColor_Side" : "عدم تطابق لون كائن OVI تحت الضوء المحوري",
            "chd_OVI_ColorInvariable" : "لون OVI غير متغير",
            "chd_OVI_IR_Invisible" : "عدم تطابق تباين كائن OVI",
            "chd_OVI_InsufficientArea" : "مساحة كائن OVI غير كافية",
            "chd_OVI_Wide_Color_Spread" : "عدم تطابق نطاق لون كائن OVI",
            "chd_Pass" : "لا توجد أخطاء",
            "chd_PhotoFalseLuminiscence": "الإضاءة الكاذبة في منطقة الصورة",
              "chd_PhotoPattern_DifferentColors": "ألوان النمط على الصورة وعلى الفراغ مختلفة",
              "chd_PhotoPattern_DifferentLinesThickness": "سماكة مختلفة لخطوط النمط",
              "chd_PhotoPattern_IR_Visible": "النمط الأمني مرئي في الأشعة تحت الحمراء",
              "chd_PhotoPattern_Interrupted": "النمط بين الصورة والفراغ يحتوي على كسر",
              "chd_PhotoPattern_InvalidColor": "لون النمط الأمني غير صالح",
              "chd_PhotoPattern_Not_Intersect": "حافة الصورة لا تتقاطع مع النمط",
              "chd_PhotoPattern_PatternNotFound": "النمط لم يتم العثور عليه في منطقة الصورة",
              "chd_PhotoPattern_Shifted": "النمط على الصورة منحرف بالنسبة للنمط على الفراغ",
              "chd_PhotoPattern_Shifted_Vert": "خطوط النمط منحرفة عمودياً بالنسبة لبعضها",
              "chd_PhotoSidesNotFound": "الحدود المطلوبة للصورة لم يتم العثور عليها",
              "chd_PhotoSize_Is_Wrong": "حجم الصورة غير صحيح",
              "chd_Photo_Corners_Is_Wrong": "زوايا الصورة لا تفي بالمتطلبات",
              "chd_Photo_IsNot_Rectangle": "شكل الصورة ليس مستطيلاً",
              "chd_PortraitComparison_NoLivePhoto": "لا توجد صورة حية",
              "chd_PortraitComparison_NoPortraitDetected": "لم يتم العثور على وجه في الصورة",
              "chd_PortraitComparison_NoServiceLicense": "لا يوجد ترخيص للخدمة",
              "chd_PortraitComparison_NoServiceReply": "الخدمة لا تستجيب",
              "chd_PortraitComparison_NotEnoughImages": "عدد الصور غير كافٍ",
              "chd_PortraitComparison_PortraitsDiffer": "الصور الشخصية لا تتطابق",
              "chd_PortraitComparison_ServiceError": "خطأ في الخدمة",
              "chd_SourcesComparisonError": "عدم تطابق البيانات من مصادر مختلفة",
              "chd_SpecksInUV": "الإضاءة الزائدة أو الوهج في الصورة تحت الأشعة فوق البنفسجية",
              "chd_SyntaxError": "خطأ في بناء الجملة",
              "chd_TextColorShouldBeBlue": "يجب أن يكون لون النص أزرق",
              "chd_TextColorShouldBeGreen": "يجب أن يكون لون النص أخضر",
              "chd_TextColorShouldBeRed": "يجب أن يكون لون النص أحمر",
              "chd_TextShouldBeBlack": "يجب أن يكون لون النص أسود",
              "chd_TooLowResolution": "دقة منخفضة جدًا للكشف عن الألياف",
              "chd_TooManyObjects": "عدد كبير جدًا من الأشياء",
              "chd_TooMuchShift": "قيمة الانحراف أكبر من القيمة المسموح بها",
              "chd_TrueLuminiscenceError": "عدم تطابق الكائنات المضيئة",
              "chd_UVDullPaperError": "خطأ في فحص الورق الباهت تحت الأشعة فوق البنفسجية",
              "chd_UVDullPaper_Blank": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة الفراغ",
              "chd_UVDullPaper_MRZ": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة MRZ",
              "chd_UVDullPaper_Photo": "فحص الورق الباهت تحت الأشعة فوق البنفسجية في منطقة الصورة",
              "chd_UncertainVerification": "لا يمكن اتخاذ قرار موثوق",
              "chd_Unknown": "رفض غير معروف",
              "chd_VisibleElementAbsent": "لا يوجد كائن مرئي تحت الأشعة تحت الحمراء",
              "strAGY": "AGY",
              "strAKADateofBirth": "تاريخ الميلاد المعروف أيضًا",
              "strAKAGivenNames": "الاسم الأول المعروف أيضًا",
              "strAKANamePrefix": "بادئة الاسم المعروف أيضًا",
              "strAKANameSuffix": "لاحقة الاسم المعروف أيضًا",
              "strAKASocialSecurityNumber": "رقم الضمان الاجتماعي المعروف أيضًا",
              "strAKASurname": "اللقب المعروف أيضًا",
              "strAKASurnameAndGivenNames": "الاسم الكامل المعروف أيضًا",
              "strALTCode": "رمز ALT",
              "strAcademicTitle": "اللقب الأكاديمي",
              "strAccessibilityCameraButton": "التقاط صورة وبدء المعالجة",
              "strAccessibilityCloseButton": "إغلاق",
              "strAccessibilityTorchButton": "مصباح يدوي",
              "strAccompaniedby": "برفقة",
              "strAddress": "عنوان",
              "strAddressArea": "منطقة",
              "strAddressBuilding": "وحدة",
              "strAddressCity": "مدينة",
              "strAddressCountry": "دولة",
              "strAddressFlat": "شقة",
              "strAddressHouse": "مبنى",
              "strAddressJurisdictionCode": "رمز الاختصاص القضائي",
              "strAddressLocation": "موقع",
              "strAddressMunicipality": "بلدية",
              "strAddressPostalCode": "الرمز البريدي",
              "strAddressState": "ولاية",
              "strAddressStreet": "شارع",
              "strAdministrativeNumber": "الرقم الإداري",
              "strAge": "عمر",
              "strAgeAtIssue": "العمر عند الإصدار",
              "strAirlineDesignatorofboardingpassissuer": "معرف شركة الطيران التي تصدر بطاقة الصعود",
              "strAirlineName": "اسم شركة الطيران",
              "strAirlineNameFrequentFlyer": "برنامج ولاء شركة الطيران للمسافرين الدائمين",
              "strAirlineNumericCode": "رمز شركة الطيران الرقمي",
              "strAirportFrom": "مطار المغادرة",
              "strAirportTo": "مطار الوصول",
              "strAllergies": "الحساسية",
              "strApplicationDoNotHavePermission": "التطبيق ليس لديه إذن لاستخدام الكاميرا، يرجى تغيير إعدادات الخصوصية",
              "strApplicationNumber": "رقم التطبيق",
              "strArtisticName": "اسم فني",
              "strAuditInformation": "رقم للتحقق",
              "strAuthentification": "التحقق من الأصالة",
              "strAuthority": "السلطة المصدرة",
              "strAuthorityCode": "رمز السلطة المصدرة",
              "strAuthorityRUS": "السلطة المصدرة (الوطنية)",
              "strAuthorizationNumber": "رقم الترخيص",
              "strAxialProtection": "الحماية العاكسة",
              "strBDBType": "نوع BDB",
              "strBankCardNumber": "رقم البطاقة البنكية",
              "strBankCardValidThru": "صلاحية البطاقة البنكية",
              "strBanknoteNumber": "رقم الورقة النقدية",
              "strBarcode": "الرمز الشريطي",
              "strBarcodeFormatCheck": "فحص تنسيق الرمز الشريطي",
              "strBenefitsNumber": "رقم الاستحقاقات",
              "strBinaryCode": "الرمز الثنائي",
              "strBiometricFormatOwner": "مالك تنسيق القياسات الحيوية",
              "strBiometricFormatType": "نوع تنسيق القياسات الحيوية",
              "strBiometricProductID": "معرف منتج القياسات الحيوية",
              "strBiometricSubtype": "نوع فرعي للقياسات الحيوية",
              "strBiometricType": "نوع القياسات الحيوية",
              "strBlankElement": "عنصر الفراغ",
            "strBloodGroup": "فصيلة الدم",
               "strBookletNumber": "رقم الكتيب",
               "strCCWUntil": "حتى CCW",
               "strCDLClass": "فئة CDL",
               "strCSCCode": "رمز CSC",
               "strCVV": "CVV/CVC",
               "strCaliber": "عيار",
               "strCameraUnavailable": "الكاميرا غير متوفرة",
               "strCardAccessNumber": "رقم البطاقة الوصول",
               "strCategory": "الفئة",
               "strCenturyDateOfBirth": "القرن من تاريخ الميلاد",
               "strChassisNumber": "رقم الهيكل",
               "strCheckInSequenceNumber": "رقم تسلسل الوصول",
               "strChildren": "الأطفال",
               "strCitizenshipOfFirstPerson": "جنسية الشخص الأول",
               "strCitizenshipOfSecondPerson": "جنسية الشخص الثاني",
               "strCivilStatus": "الحالة المدنية",
               "strColorDynamic": "ديناميكيات اللون",
               "strCommercialVehicleCodes": "رموز المركبات التجارية",
               "strCompanyName": "اسم الشركة",
               "strCompartmentCode": "رمز الحجرة",
               "strComplexion": "الملمس",
               "strComplianceType": "نوع الامتثال",
               "strConditions": "الشروط",
               "strConfiguration": "التكوين",
               "strControlNo": "رقم التحكم",
               "strCopy": "نسخة",
               "strCourtCode": "رمز المحكمة",
               "strCty": "مقاطعة",
               "strCurrentDate": "التاريخ الحالي",
               "strCustodyInfo": "معلومات الحضانة",
               "strDFTAppDirectory": "دليل التطبيق",
               "strDFTCertificate": "شهادة",
               "strDG1": "المنطقة القراءة الآلية (DG1)",
               "strDG10": "غير محدد (DG10)",
               "strDG11": "تفاصيل شخصية إضافية (DG11)",
               "strDG12": "تفاصيل وثيقة إضافية (DG12)",
               "strDG13": "تفاصيل اختيارية (DG13)",
               "strDG14": "معلومات EAC (DG14)",
               "strDG15": "معلومات المصادقة النشطة (DG15)",
               "strDG16": "الشخص (أشخاص) للإعلام (DG16)",
               "strDG17": "DG17",
               "strDG18": "DG18",
               "strDG19": "DG19",
               "strDG2": "بيانات الوجه (DG2)",
               "strDG20": "DG20",
               "strDG3": "بيانات بيومترية - بصمات الأصابع (DG3)",
               "strDG4": "بيانات بيومترية - بيانات القزحية (DG4)",
               "strDG5": "صور البورتريه (DG5)",
               "strDG6": "غير محدد (DG6)",
               "strDG7": "صورة التوقيع/العلامة العادية (DG7)",
               "strDG8": "غير محدد (DG8)",
               "strDG9": "غير محدد (DG9)",
               "strDLCDLRestrictionCode": "رمز قيود رخصة القيادة التجارية",
               "strDLClass": "فئة رخصة القيادة",
               "strDLClassCodeA1From": "فئة رخصة القيادة A1 صالحة من",
               "strDLClassCodeA1Notes": "رموز فئة رخصة القيادة A1",
               "strDLClassCodeA1To": "فئة رخصة القيادة A1 صالحة إلى",
               "strDLClassCodeA2From": "فئة رخصة القيادة A2 صالحة من",
               "strDLClassCodeA2Notes": "رموز فئة رخصة القيادة A2",
               "strDLClassCodeA2To": "فئة رخصة القيادة A2 صالحة إلى",
               "strDLClassCodeA3From": "فئة رخصة القيادة A3 صالحة من",
               "strDLClassCodeA3Notes": "رموز فئة رخصة القيادة A3",
               "strDLClassCodeA3To": "فئة رخصة القيادة A3 صالحة إلى",
               "strDLClassCodeAFrom": "فئة رخصة القيادة A صالحة من",
               "strDLClassCodeAMFrom": "فئة رخصة القيادة AM صالحة من",
               "strDLClassCodeAMNotes": "رموز فئة رخصة القيادة AM",
               "strDLClassCodeAMTo": "فئة رخصة القيادة AM صالحة إلى",
               "strDLClassCodeANotes": "رموز فئة رخصة القيادة A",
               "strDLClassCodeATo": "فئة رخصة القيادة A صالحة إلى",
               "strDLClassCodeB1From": "فئة رخصة القيادة B1 صالحة من",
               "strDLClassCodeB1Notes": "رموز ف",
            "strDLClassCodeB1To": "فئة رخصة القيادة B1 صالحة حتى",
              "strDLClassCodeB2EFrom": "فئة رخصة القيادة B2E صالحة من",
              "strDLClassCodeB2ENotes": "رموز فئة رخصة القيادة B2E",
              "strDLClassCodeB2ETo": "فئة رخصة القيادة B2E صالحة حتى",
              "strDLClassCodeB2From": "فئة رخصة القيادة B2 صالحة من",
              "strDLClassCodeB2Notes": "رموز فئة رخصة القيادة B2",
              "strDLClassCodeB2To": "فئة رخصة القيادة B2 صالحة حتى",
              "strDLClassCodeBEFrom": "فئة رخصة القيادة BE صالحة من",
              "strDLClassCodeBENotes": "رموز فئة رخصة القيادة BE",
              "strDLClassCodeBETo": "فئة رخصة القيادة BE صالحة حتى",
              "strDLClassCodeBFrom": "فئة رخصة القيادة B صالحة من",
              "strDLClassCodeBNotes": "رموز فئة رخصة القيادة B",
              "strDLClassCodeBTPFrom": "فئة رخصة القيادة BTP صالحة من",
              "strDLClassCodeBTPNotes": "رموز فئة رخصة القيادة BTP",
              "strDLClassCodeBTPTo": "فئة رخصة القيادة BTP صالحة حتى",
              "strDLClassCodeBTo": "فئة رخصة القيادة B صالحة حتى",
              "strDLClassCodeC1EFrom": "فئة رخصة القيادة C1E صالحة من",
              "strDLClassCodeC1ENotes": "رموز فئة رخصة القيادة C1E",
              "strDLClassCodeC1ETo": "فئة رخصة القيادة C1E صالحة حتى",
              "strDLClassCodeC1From": "فئة رخصة القيادة C1 صالحة من",
              "strDLClassCodeC1Notes": "رموز فئة رخصة القيادة C1",
              "strDLClassCodeC1To": "فئة رخصة القيادة C1 صالحة حتى",
              "strDLClassCodeC2From": "فئة رخصة القيادة C2 صالحة من",
              "strDLClassCodeC2Notes": "رموز فئة رخصة القيادة C2",
              "strDLClassCodeC2To": "فئة رخصة القيادة C2 صالحة حتى",
              "strDLClassCodeC3From": "فئة رخصة القيادة C3 صالحة من",
              "strDLClassCodeC3Notes": "رموز فئة رخصة القيادة C3",
              "strDLClassCodeC3To": "فئة رخصة القيادة C3 صالحة حتى",
              "strDLClassCodeCAFrom": "فئة رخصة القيادة CA صالحة من",
              "strDLClassCodeCANotes": "رموز فئة رخصة القيادة CA",
              "strDLClassCodeCATo": "فئة رخصة القيادة CA صالحة حتى",
              "strDLClassCodeCEFrom": "فئة رخصة القيادة CE صالحة من",
              "strDLClassCodeCENotes": "رموز فئة رخصة القيادة CE",
              "strDLClassCodeCETo": "فئة رخصة القيادة CE صالحة حتى",
              "strDLClassCodeCFrom": "فئة رخصة القيادة C صالحة من",
              "strDLClassCodeCNotes": "رموز فئة رخصة القيادة C",
              "strDLClassCodeCTo": "فئة رخصة القيادة C صالحة حتى",
              "strDLClassCodeD1EFrom": "فئة رخصة القيادة D1E صالحة من",
              "strDLClassCodeD1ENotes": "رموز فئة رخصة القيادة D1E",
              "strDLClassCodeD1ETo": "فئة رخصة القيادة D1E صالحة حتى",
              "strDLClassCodeD1From": "فئة رخصة القيادة D1 صالحة من",
              "strDLClassCodeD1Notes": "رموز فئة رخصة القيادة D1",
              "strDLClassCodeD1To": "فئة رخصة القيادة D1 صالحة حتى",
              "strDLClassCodeD2From": "فئة رخصة القيادة D2 صالحة من",
              "strDLClassCodeD2Notes": "رموز فئة رخصة القيادة D2",
              "strDLClassCodeD2To": "فئة رخصة القيادة D2 صالحة حتى",
              "strDLClassCodeDEFrom": "فئة رخصة القيادة DE صالحة من",
            "strDLClassCodeDENotes" : "DL category DE codes",
            "strDLClassCodeDETo" : "DL category DE valid to",
            "strDLClassCodeDFrom" : "DL category D valid from",
            "strDLClassCodeDNotes" : "DL category D codes",
            "strDLClassCodeDTo" : "DL category D valid to",
            "strDLClassCodeEFrom" : "DL category E valid from",
            "strDLClassCodeENotes" : "DL category E codes",
            "strDLClassCodeETo" : "DL category E valid to",
            "strDLClassCodeFA1From" : "DL category FA1 valid from",
            "strDLClassCodeFA1Notes" : "DL category FA1 codes",
            "strDLClassCodeFA1To" : "DL category FA1 valid to",
            "strDLClassCodeFAFrom" : "DL category FA valid from",
            "strDLClassCodeFANotes" : "DL category FA codes",
            "strDLClassCodeFATo" : "DL category FA valid to",
            "strDLClassCodeFBFrom" : "DL category FB valid from",
            "strDLClassCodeFBNotes" : "DL category FB codes",
            "strDLClassCodeFBTo" : "DL category FB valid to",
            "strDLClassCodeFFrom" : "DL category F valid from",
            "strDLClassCodeFNotes" : "DL category F codes",
            "strDLClassCodeFTo" : "DL category F valid to",
            "strDLClassCodeG1From" : "DL category G1 valid from",
            "strDLClassCodeG1Notes" : "DL category G1 codes",
            "strDLClassCodeG1To" : "DL category G1 valid to",
            "strDLClassCodeGFrom" : "DL category G valid from",
            "strDLClassCodeGNotes" : "DL category G codes",
            "strDLClassCodeGTo" : "DL category G valid to",
            "strDLClassCodeHCFrom" : "DL category HC valid from",
            "strDLClassCodeHCNotes" : "DL category HC codes",
            "strDLClassCodeHCTo" : "DL category HC valid to",
            "strDLClassCodeHFrom" : "DL category H valid from",
            "strDLClassCodeHNotes" : "DL category H codes",
            "strDLClassCodeHRFrom" : "DL category HR valid from",
            "strDLClassCodeHRNotes" : "DL category HR codes",
            "strDLClassCodeHRTo" : "DL category HR valid to",
            "strDLClassCodeHTo" : "DL category H valid to",
            "strDLClassCodeIFrom" : "DL category I valid from",
            "strDLClassCodeINotes" : "DL category I codes",
            "strDLClassCodeITo" : "DL category I valid to",
            "strDLClassCodeJFrom" : "DL category J valid from",
            "strDLClassCodeJNotes" : "DL category J codes",
            "strDLClassCodeJTo" : "DL category J valid to",
            "strDLClassCodeKFrom" : "DL category K valid from",
            "strDLClassCodeKNotes" : "DL category K codes",
            "strDLClassCodeKTo" : "DL category K valid to",
            "strDLClassCodeLCFrom" : "DL category LC valid from",
            "strDLClassCodeLCNotes" : "DL category LC codes",
            "strDLClassCodeLCTo" : "DL category LC valid to",
            "strDLClassCodeLFrom" : "DL category L valid from",
            "strDLClassCodeLKFrom" : "DL category LK valid from",
            "strDLClassCodeLKNotes" : "DL category LK codes",
            "strDLClassCodeLKTo" : "DL category LK valid to",
            "strDLClassCodeLNotes" : "DL category L codes",
            "strDLClassCodeLRFrom" : "DL category LR valid from",
            "strDLClassCodeLRNotes" : "DL category LR codes",
            "strDLClassCodeLRTo" : "DL category LR valid to",
            "strDLClassCodeLTo" : "DL category L valid to",
            "strDLClassCodeMCFrom" : "DL category MC valid from",
            "strDLClassCodeMCNotes" : "DL category MC codes",
            "strDLClassCodeMCTo" : "DL category MC valid to",
            "strDLClassCodeMFrom" : "DL category M valid from",
            "strDLClassCodeMNotes" : "DL category M codes",
            "strDLClassCodeMRFrom" : "DL category MR valid from",
            "strDLClassCodeMRNotes" : "DL category MR codes",
            "strDLClassCodeMRTo" : "DL category MR valid to",
            "strDLClassCodeMTo" : "DL category M valid to",
            "strDLClassCodeNFrom" : "DL category N valid from",
            "strDLClassCodeNNotes" : "DL category N codes",
            "strDLClassCodeNTo" : "DL category N valid to",
            "strDLClassCodeREFrom" : "DL category RE valid from",
            "strDLClassCodeRENotes" : "DL category RE codes",
            "strDLClassCodeRETo" : "DL category RE valid to",
            "strDLClassCodeRFrom" : "DL category R valid from",
            "strDLClassCodeRNotes" : "DL category R codes",
            "strDLClassCodeRTo" : "DL category R valid to",
            "strDLClassCodeSFrom" : "DL category S valid from",
            "strDLClassCodeSNotes" : "DL category S codes",
            "strDLClassCodeSTo" : "DL category S valid to",
            "strDLClassCodeTBFrom" : "DL category TB valid from",
            "strDLClassCodeTBNotes" : "DL category TB codes",
            "strDLClassCodeTBTo" : "DL category TB valid to",
            "strDLClassCodeTFrom" : "DL category T valid from",
            "strDLClassCodeTMFrom" : "DL category TM valid from",
            "strDLClassCodeTMNotes" : "DL category TM codes",
            "strDLClassCodeTMTo" : "DL category TM valid to",
            "strDLClassCodeTNotes" : "DL category T codes",
            "strDLClassCodeTRFrom" : "DL category TR valid from",
            "strDLClassCodeTRNotes" : "DL category TR codes",
            "strDLClassCodeTRTo" : "DL category TR valid to",
            "strDLClassCodeTTo" : "DL category T valid to",
            "strDLClassCodeTVFrom" : "DL category TV valid from",
            "strDLClassCodeTVNotes" : "DL category TV codes",
            "strDLClassCodeTVTo" : "DL category TV valid to",
            "strDLClassCodeVFrom" : "DL category V valid from",
            "strDLClassCodeVNotes" : "DL category V codes",
            "strDLClassCodeVTo" : "DL category V valid to",
            "strDLClassCodeWFrom" : "DL category W valid from",
            "strDLClassCodeWNotes" : "DL category W codes",
            "strDLClassCodeWTo" : "DL category W valid to",
            "strDLDuplicateDate" : "Date of duplicate issue",
            "strDLEndorsed" : "DL endorsement code",
            "strDLIssType" : "Card type",
            "strDLRecordCreated" : "Record created",
            "strDLRestrictionCode" : "DL Restriction Code",
            "strDLUnder18Date" : "Date of 18th birthday",
            "strDLUnder19Date" : "Date of 19th birthday",
            "strDLUnder21Date" : "Date of 21st birthday",
            "strDNINumber" : "DNI number",
            "strDSCertificateIssuer" : "DS certificate issuer",
            "strDSCertificateSubject" : "DS certificate subject",
            "strDSCertificateValidFrom" : "DS certificate valid from",
            "strDSCertificateValidTo" : "DS certificate valid to",
            "strDUFNumber" : "DUF number",
            "strDataDiscriminator" : "Data discriminator",
            "strDateFirstRenewal" : "Date of first renewal",
            "strDateOfBirthOfHusband" : "Date of birth of husband",
            "strDateOfBirthOfWife" : "Date of birth of wife",
            "strDateOfInsuranceExpiry" : "Expiry date of insurance",
            "strDateSecondRenewal" : "Date of second renewal",
            "strDateofBirth" : "Date of birth",
            "strDateofBirthCheckDigit" : "Check digit for date of birth",
            "strDateofBirthChecksum" : "Checksum for date of birth",
            "strDateofCreation" : "Creation date",
            "strDateofExpiry" : "Date of expiry",
            "strDateofExpiryCheckDigit" : "Check digit for date of expiry",
            "strDateofExpiryChecksum" : "Checksum for date of expiry",
            "strDateofFlight" : "Date of flight",
            "strDateofIssue" : "Date of issue",
            "strDateofIssueBoardingPass" : "Date of boarding pass issue",
            "strDateofIssueCheckDigit" : "Check digit for date of issue",
            "strDateofIssueChecksum" : "Checksum for date of issue",
            "strDateofPersonalization" : "Personalization date",
            "strDateofRegistration" : "Date of registration",
            "strDay" : "Day",
            "strDepartment" : "Department",
            "strDeptNumber" : "Department number",
            "strDestination" : "Destination",
            "strDiscretionaryData" : "Discretionary data",
            "strDoDNumber" : "DoD number",
            "strDocumentClassCode" : "Document class code",
            "strDocumentClassName" : "Document class",
            "strDocumentDiscriminator" : "Document discriminator",
            "strDocumentNumber" : "Document number",
            "strDocumentNumberCheckDigit" : "Check digit for document number",
            "strDocumentNumberChecksum" : "Checksum for document number",
            "strDocumentSeries" : "Document series",
            "strDocumentTooSmall" : "ضع المستند في الإطار",
            "strDonor" : "Donor",
            "strDossierNumber" : "Dossier number",
            "strDurationofStay" : "Duration of stay",
            "strECEnvironmentalType" : "Vehicle environmental type",
            "strEDLDG1" : "Text data elements (DG1)",
            "strEDLDG10" : "not defined (DG10)",
            "strEDLDG11" : "Optional domestic data (DG11)",
            "strEDLDG12" : "Non-match alert (DG12)",
            "strEDLDG13" : "Active Authentication info (DG13)",
            "strEDLDG14" : "EAC info (DG14)",
            "strEDLDG2" : "License holder information (DG2)",
            "strEDLDG3" : "Issuing authority details (DG3)",
            "strEDLDG4" : "Portrait image (DG4)",
            "strEDLDG5" : "Signature / usual mark image (DG5)",
            "strEDLDG6" : "Biometry - Facial data (DG6)",
            "strEDLDG7" : "Biometry - Fingerprint(s) (DG7)",
            "strEDLDG8" : "Biometry - Iris Data (DG8)",
            "strEDLDG9" : "Biometry - Other (DG9)",
            "strEFCOM" : "EF.COM",
            "strEFCVCA" : "EF.CVCA",
            "strEFCardAccess" : "EF.CardAccess",
            "strEFCardSecurity" : "EF.CardSecurity",
            "strEFChipSecurity" : "EF.ChipSecurity",
            "strEFSOD" : "EF.SOD",
            "strEQVCode" : "EQV code",
            "strElectronicTicketIndicator" : "Electronic ticket indicator",
            "strElement" : "Element",
            "strEndorsementExpirationDate" : "Endorsement expiration date",
            "strEngineModel" : "Engine model",
            "strEngineNumber" : "Engine number",
            "strEnginePower" : "Engine power",
            "strEngineVolume" : "Engine volume",
            "strError" : "Error",
            "strExamDate" : "Exam date",
            "strExeptInTanks" : "Except in tanks",
            "strEye" : "Iris",
            "strEyesColor" : "Eye color",
            "strFaculty" : "Faculty",
            "strFalseLuminescence" : "Excessive luminescence",
            "strFamilyName" : "Surname/given name at birth",
            "strFamilyNameTruncation" : "Truncated surname/given name at birth",
            "strFastTrack" : "Fast Track service",
            "strFatherCountryOfBirth" : "Father's country of birth",
            "strFatherDateOfBirth" : "Father's date of birth",
            "strFatherGivenName" : "Father's given name",
            "strFatherPersonalNumber" : "Father's personal number",
            "strFatherPlaceOfBirth" : "Father's place of birth",
            "strFatherSurname" : "Father's surname",
            "strFathersName" : "Father's name",
            "strFathersNameRUS" : "Father's name (National)",
            "strFederalElections" : "Federal elections",
            "strFee" : "Fee",
            "strFieldFromMRZ" : "Field from MRZ",
            "strFieldTypeDocumentImage" : "Document image",
            "strFillElement" : "Filling element",
            "strFinalCheckDigit" : "Final check digit",
            "strFinalChecksum" : "Final checksum",
            "strFingerprint" : "Fingerprint",
            "strFirstIssueDate" : "First issue date",
            "strFirstNameTruncation" : "First name truncation",
            "strFlightNumber" : "Flight number",
            "strFolioNumber" : "Folio number",
            "strFormOfEducation" : "Form of education",
            "strFreeBaggageAllowance" : "Free baggage allowance",
            "strFrequentFlyerAirlineDesignator" : "Frequent flyer airline designator",
            "strFrequentFlyerNumber" : "Frequent flyer number",
            "strFromAirportCode" : "Code of the airport of departure",
            "strFuelType" : "Fuel type",
            "strGNIBNumber" : "GNIB number",
            "strGhostPortrait" : "Ghost portrait",
            "strGivenNames" : "Given name",
            "strGivenNamesRUS" : "Given name (National)",
            "strGlaresOnDocument" : "تجنب الوهج على الوثيقة",
            "strGrandfatherName" : "Grandfather's name",
            "strHairColor" : "Hair color",
            "strHealthNumber" : "Health insurance number",
            "strHeight" : "Height",
            "strHoldDocumentStraight" : "أمسك الوثيقة بشكل مستقيم",
            "strHoloSimple" : "Hologram availability",
            "strHoloVerifyDinamic" : "Verify dynamic hologram",
            "strHoloVerifyMultiStatic" : "Verify Multi Static Hologram",
            "strHoloVerifyStatic" : "Verify Static Hologram",
            "strHolograms" : "Holograms",
            "strIPI" : "IPI (invisible personal information)",
            "strIRB900" : "IR B900 ink",
            "strIRVis" : "IR transparency",
            "strISOIssuerIDNumber" : "ID number of ISO issuer",
            "strIdentifier" : "Identifier",
            "strIdentityCardNumber" : "Identity card number",
            "strIdentityCardNumberCheckDigit" : "Check digit for identity card number",
            "strIdentityCardNumberChecksum" : "Checksum for identity card number",
            "strImagePattern" : "Image patterns",
            "strInTanks" : "In tanks",
            "strInventoryNumber" : "Inventory number",
            "strInvitationNumber" : "Invitation number",
            "strInvitationNumberCheckDigit" : "Check digit for invitation number",
            "strInvitationNumberChecksum" : "Checksum for invitation number",
            "strInvitedBy" : "Invited by",
            "strIssueTimestamp" : "Issue time",
            "strIssuingStateCode" : "Issuing state code",
            "strIssuingStateName" : "Issuing state",
            "strJurisdictionEndorsementCode" : "Jurisdiction endorsement code",
            "strJurisdictionRestrictionCode" : "Jurisdiction restriction code",
            "strJurisdictionVehicleClass" : "Jurisdiction vehicle class",
            "strKeepDeviceStill" : "امسك الجهاز بثبات",
            "strLicenseNumber" : "License number",
            "strLimitedDurationDocumentIndicator" : "Indicator of document limited duration",
            "strLine1CheckDigit" : "Check digit for line 1",
            "strLine1Checksum" : "Checksum for line 1",
            "strLine1OptionalData" : "Optional data from line 1",
            "strLine2CheckDigit" : "Check digit for line 2",
            "strLine2Checksum" : "Checksum for line 2",
            "strLine2OptionalData" : "Optional data from line 2",
            "strLine3CheckDigit" : "Check digit for line 3",
            "strLine3Checksum" : "Checksum for line 3",
            "strLine3OptionalData" : "Optional data from line 3",
            "strLookingDocument" : "جاري البحث عن وثيقة...",
            "strMCNoviceDate" : "Expiry date of Motorcycle Novice status",
            "strMRZ" : "MRZ",
            "strMRZLinesICAORFID" : "MRZ lines from ICAO RFID",
            "strMRZString1" : "MRZ line 1",
            "strMRZString2" : "MRZ line 2",
            "strMRZString3" : "MRZ line 3",
            "strMRZStrings" : "MRZ lines",
            "strMRZStringsWithCorrectCheckSums" : "MRZ lines with correct checksums",
            "strMRZType" : "MRZ Type",
            "strMailingAddressCity" : "Mailing address - city",
            "strMailingAddressJurisdictionCode" : "Mailing address - jurisdiction code",
            "strMailingAddressPostalCode" : "Mailing address - postal code",
            "strMailingAddressStreet" : "Mailing address - street",
            "strMake" : "Make",
            "strMaritalStatus" : "Marital status",
            "strMaxMassofTrailerBraked" : "Max mass of trailer (braked)",
            "strMaxMassofTrailerUnbraked" : "Max mass of trailer (unbraked)",
            "strMaxSpeed" : "Max speed",
            "strMedicalIndicatorCodes" : "Medical notes/codes",
            "strMiddleName" : "Middle name",
            "strMiddleNameTruncation" : "Middle name truncation",
            "strMifareData" : "MIFARE data",
            "strMifareValidity" : "MIFARE validity",
            "strMilitaryBookNumber" : "Military ID number",
            "strModel" : "Model",
            "strMonth" : "Month",
            "strMortgageBy" : "Mortgage by",
            "strMotherCountryOfBirth" : "Mother's country of birth",
            "strMotherDateOfBirth" : "Mother's date of birth",
            "strMotherGivenName" : "Mother's given name",
            "strMotherPersonalNumber" : "Mother's personal number",
            "strMotherPlaceOfBirth" : "Mother's place of birth",
            "strMotherSurname" : "Mother's surname",
            "strMothersName" : "Mother's name",
            "strNamePrefix" : "Name prefix",
            "strNameSuffix" : "Name suffix",
            "strNationality" : "Nationality",
            "strNationalityCode" : "Nationality code",
            "strNonResidentIndicator" : "Non-resident indicator",
            "strNone" : "None",
            "strNotDefined" : "Undefined",
            "strNumberOfCardIssuance" : "Number of card issuances",
            "strNumberOfCardIssuanceCheckDigit" : "Check digit for number of card issuances",
            "strNumberOfCardIssuanceChecksum" : "Checksum for number of card issuances",
            "strNumberOfCylinders" : "Number of cylinders",
            "strNumberofAxels" : "Number of axles",
            "strNumberofDuplicates" : "Number of duplicates",
            "strNumberofEntries" : "Number of entries",
            "strNumberofSeats" : "Number of seats",
            "strNumberofStandingPlaces" : "Number of standing places",
            "strOCRNumber" : "OCR number",
            "strOK" : "OK",
            "strObservations" : "Observations",
            "strOldDateOfIssue" : "Old date of issue",
            "strOldDocumentNumber" : "Old document number",
            "strOldPlaceOfIssue" : "Old place of issue",
            "strOptionalData" : "Optional data",
            "strOptionalDataCheckDigit" : "Check digit for optional data",
            "strOptionalDataChecksum" : "Checksum for optional data",
            "strOptionalDetails" : "Optional details",
            "strOrganization" : "Organization",
            "strOther" : "Other",
            "strOtherName" : "Other name",
            "strOtherPersonName" : "Other person, name",
            "strOtherValidID" : "Other valid IDs",
            "strOwner" : "Owner",
            "strPDF417Codec" : "PDF417 codec",
            "strPNRCode" : "PNR code",
            "strParrentsGivenNames" : "Parents' given names",
            "strPassportNumber" : "Passport number",
            "strPassportNumberCheckDigit" : "Check digit for passport number",
            "strPassportNumberChecksum" : "Checksum for passport number",
            "strPatronHeaderVersion" : "Patron header version",
            "strPatternDifferentLinesThickness" : "Comparison of the thickness of the pattern lines",
            "strPatternIRInvisible" : "Invisible pattern in IR",
            "strPatternNotInterrupted" : "No breaks",
            "strPatternNotShifted" : "Pattern elements are not shifted",
            "strPatternSameColors" : "Same colors of the pattern",
            "strPayGrade" : "Pay grade",
            "strPayloadCapacity" : "Payload capacity",
            "strPermissibleAxleLoad" : "Permissible axle load",
            "strPermitDLClass" : "Permit class",
            "strPermitDateofExpiry" : "Permit expiry date",
            "strPermitDateofIssue" : "Permit issue date",
            "strPermitEndorsed" : "Permit endorsement code",
            "strPermitIdentifier" : "Permit identifier",
            "strPermitRestrictionCode" : "Permit restriction code",
            "strPersonToNotifyAddress" : "Notify person: Address",
            "strPersonToNotifyDateofRecord" : "Notify person: Date of record",
            "strPersonToNotifyName" : "Notify person: Name",
            "strPersonToNotifyPhone" : "Notify person: Phone",
            "strPersonalNumber" : "Personal number",
            "strPersonalNumberCheckDigit" : "Check digit for personal number",
            "strPersonalNumberChecksum" : "Checksum for personal number",
            "strPersonalSummary" : "Personal data summary",
            "strPersonalizationSN" : "Serial number of personalization",
            "strPhone" : "Phone",
            "strPhotoArea" : "Photo area",
            "strPhotoColor" : "Color of the photo",
            "strPhotoCorners" : "Corners of the photo",
            "strPhotoElement" : "Photo element",
            "strPhotoEmbedType" : "Photo embedding type",
            "strPhotoProcessing" : "Photo processing...",
            "strPhotoShape" : "Shape of the photo",
            "strPhotoSizeCheck" : "Size check",
            "strPlaceDocumentInFrame" : "ضع المستند في الإطار",
            "strPlaceOfBirthRUS" : "Place of birth (National)",
            "strPlaceOfBirthStateCode" : "State code of birthplace",
            "strPlaceOfExamination" : "Place of examination",
            "strPlaceOfIssue" : "Place of issue",
            "strPlacePhoneOnDoc" : "Place the phone on the document please",
            "strPlaceofBirth" : "Place of birth",
            "strPlaceofBirthArea" : "Area of birthplace",
            "strPlaceofRegistration" : "Place of registration",
            "strPoliceDistrict" : "Police district",
            "strPortrait" : "Portrait",
            "strPortraitComparison" : "Comparison of the portraits",
            "strPortraitOfChild" : "Portrait of child",
            "strPortraitVSCamera" : "Portrait vs Camera image",
            "strPortraitVSGhost" : "Portrait vs Ghost photo",
            "strPortraitVSRFID" : "Portrait vs RFID chip portrait",
            "strPowerWeightRatio" : "Power-to-weight ratio",
            "strPrecinct" : "Precinct",
            "strPrepareCamera" : "Preparing the camera...",
            "strPresentNextPage" : "يرجى تقديم الصفحة التالية",
            "strPreviousType" : "Type/number of the previous document",
            "strProcessingDocument" : "معالجة الملف...",
            "strProfession" : "Profession",
            "strProfessionalIdNumber" : "Professional ID number",
            "strProofOfCitizenship" : "Proof of citizenship",
            "strPseudoCode" : "Pseudocode",
            "strPurposeOfEntry" : "Purpose of entry",
            "strRFIDVSCamera" : "RFID chip portrait vs Camera image",
            "strRaceEthnicity" : "Race/ethnicity",
            "strRank" : "Rank",
            "strReadingRFID" : "Reading RFID chip data",
            "strReadingRFIDDGiOS" : "Reading RFID %@ data",
            "strRecognizedDocumentType" : "Document type",
            "strReferenceNumber" : "Unique number",
            "strReferenceNumberCheckDigit" : "Unique number check digit",
            "strReferenceNumberChecksum" : "Unique number checksum",
            "strRegCertBodyNumber" : "Body number",
            "strRegCertBodyType" : "Body type",
            "strRegCertCarColor" : "Vehicle color",
            "strRegCertCarMark" : "Vehicle make",
            "strRegCertCarModel" : "Vehicle model",
            "strRegCertCarType" : "Vehicle type",
            "strRegCertMaxWeight" : "Max permissible weight",
            "strRegCertRegNumber" : "Registration number",
            "strRegCertRegNumberCheckDigit" : "Check digit for registration number",
            "strRegCertRegNumberChecksum" : "Checksum for registration number",
            "strRegCertVIN" : "Vehicle identification number",
            "strRegCertVINCheckDigit" : "Check digit for VIN",
            "strRegCertVINChecksum" : "Checksum for VIN",
            "strRegCertVehicleITSCode" : "Vehicle ITS code",
            "strRegCertWeight" : "Unladen mass",
            "strRelationship" : "Relationship",
            "strReligion" : "Religion",
            "strRemainderTerm" : "Months to expire",
            "strResidentFrom" : "Resident from",
            "strResidentUntil" : "Resident until",
            "strRetirementNumber" : "Retirement number",
            "strRevisionDate" : "Revision date",
            "strRoomNumber" : "Room number",
            "strSBHIntegrityOptions" : "SBH integrity options",
            "strSBHSecurityOptions" : "SBH security options",
            "strSeatNumber" : "Seat number",
            "strSecondSurname" : "Second surname",
            "strSection" : "Section",
            "strSecurityText" : "Security text",
            "strSelecteeIndicator" : "Selectee indicator",
            "strSequenceNumber" : "Sequence number",
            "strSerialNumber" : "Serial number",
            "strSettings" : "Settings",
            "strSex" : "Sex",
            "strSignature" : "Signature",
            "strSkinColor" : "Skin color",
            "strSocialSecurityNumber" : "Social insurance number",
            "strSpCode" : "Special code",
            "strSpecialNotes" : "Special notes",
            "strSponsor" : "Sponsor",
            "strSponsorSSN" : "Sponsor SSN",
            "strSponsorService" : "Sponsor service",
            "strSponsorStatus" : "Sponsor status",
            "strStamp" : "Stamp",
            "strStampNumber" : "Stamp number",
            "strStatusDateofExpiry" : "Status Expiry Date",
            "strSurname" : "Surname",
            "strSurnameAndGivenNames" : "Surname and given names",
            "strSurnameAndGivenNamesCheckDigit" : "Check digit for surname and given names",
            "strSurnameAndGivenNamesChecksum" : "Checksum for surname and given names",
            "strSurnameAndGivenNamesRUS" : "Surname and given names (National)",
            "strSurnameAtBirth" : "Surname at birth",
            "strSurnameOfHusbandAfterRegistration" : "Surname of husband after registration",
            "strSurnameOfWifeAfterRegistration" : "Surname of wife after registration",
            "strSurnameofSpose" : "Spouse's surname",
            "strTax" : "Tax",
            "strTaxNumber" : "Tax number",
            "strTelexCode" : "Telegraph code",
            "strTerritorialValidity" : "Territorial validity",
            "strTicketNumber" : "Ticket number",
            "strTitle" : "Position",
            "strToAirportCode" : "Code of the airport of arrival",
            "strTorchUnavailable" : "Torch unavailable",
            "strTrackingNumber" : "Tracking number",
            "strTrailerHitch" : "Trailer hitch",
            "strTransactionNumber" : "Transaction number",
            "strTransmissionType" : "Transmission type",
            "strTypeApprovalNumber" : "Type of approval number",
            "strURL" : "URL",
            "strUSCIS" : "USCIS",
            "strUV" : "UV",
            "strUVFibers" : "UV security fibers",
            "strUVLuminescence" : "UV dull paper check",
            "strUnableCaptureMedia" : "Camera configuration failed",
            "strUniqueCustomerIdentifier" : "Unique customer identifier",
            "strVRCDataObjectEntry" : "Vehicle data from the DG1 data group",
            "strValidityPeriod" : "Validity period",
            "strVehicleCategory" : "Vehicle category",
            "strVeteran" : "Veteran",
            "strVisaClass" : "Visa Class",
            "strVisaID" : "Visa ID",
            "strVisaIDCheckDigit" : "Check digit for visa ID",
            "strVisaIDChecksum" : "Checksum for visa ID",
            "strVisaIDRUS" : "Visa ID (National)",
            "strVisaNumber" : "Visa Number",
            "strVisaNumberCheckDigit" : "Check digit for visa number",
            "strVisaNumberChecksum" : "Checksum for visa number",
            "strVisaSubClass" : "Visa subclass",
            "strVisaType" : "Visa type",
            "strVisaValidFrom" : "Visa valid from",
            "strVisaValidUntil" : "Visa valid until",
            "strVisaValidUntilCheckDigit" : "Check digit for visa expiry date",
            "strVisaValidUntilChecksum" : "Checksum for visa expiry date",
            "strVisibleLight" : "Visible light",
            "strVoter" : "Voter",
            "strVoterKey" : "Voter Key",
            "strVoucherNumber" : "Voucher number",
            "strWeight" : "Weight",
            "strWeightPound" : "Weight (pound)",
            "strYear" : "Year",
            "strYearsSinceIssue" : "Years since issue",
            "streIDPlaceOfBirthCity" : "Place of Birth: City",
            "streIDPlaceOfBirthCountry" : "Place of Birth: Country",
            "streIDPlaceOfBirthState" : "Place of Birth: State",
            "streIDPlaceOfBirthStreet" : "Place of Birth: Street",
            "streIDPlaceOfBirthZipcode" : "Place of Birth: Postal code",
            "streIDResidencePermit1" : "Residence permit 1",
            "streIDResidencePermit2" : "Residence permit 2",
            "strfppLeftIndexFinger" : "Left index finger",
            "strfppLeftLittleFinger" : "Left little finger",
            "strfppLeftMiddleFinger" : "Left middle finger",
            "strfppLeftRingFinger" : "Left ring finger",
            "strfppLeftThumb" : "Left thumb",
            "strfppRightIndexFinger" : "Right index finger",
            "strfppRightLittleFinger" : "Right little finger",
            "strfppRightMiddleFinger" : "Right middle finger",
            "strfppRightRingFinger" : "Right ring finger",
            "strfppRightThumb" : "Right thumb",
        ]
    }
}
